<?php
ob_start(); session_start();
if(!isset($_SESSION['logged_in'])||$_SESSION['logged_in']!==true){$api=isset($_GET['action'])||($_SERVER['REQUEST_METHOD']??'')==='POST';if($api){while(ob_get_level())ob_end_clean();header('Content-Type: application/json');http_response_code(401);echo json_encode(['success'=>false,'message'=>'Your session has expired. Please log in again.']);exit;}header('Location: login.php');exit;}
/* Self-contained database layer to avoid deployment filename/dependency failures. */
function license_db(): PDO {
    static $db=null; if($db instanceof PDO)return $db;
    $url=getenv('DATABASE_URL'); if(!$url)throw new RuntimeException('DATABASE_URL is not configured in Render.');
    if(!in_array('pgsql',PDO::getAvailableDrivers(),true))throw new RuntimeException('PDO PostgreSQL driver (pdo_pgsql) is not enabled.');
    $p=parse_url($url); if(!$p||empty($p['host'])||empty($p['user'])||empty($p['path']))throw new RuntimeException('DATABASE_URL is invalid.');
    $dsn=sprintf('pgsql:host=%s;port=%d;dbname=%s',$p['host'],(int)($p['port']??5432),ltrim($p['path'],'/'));
    $db=new PDO($dsn,urldecode($p['user']),urldecode($p['pass']??''),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]); return $db;
}
function ensure_license_table(): void {
 $db=license_db();
 $db->exec("CREATE TABLE IF NOT EXISTS public.coffee_licenses (
 id BIGSERIAL PRIMARY KEY, license_sale_season VARCHAR(20) NOT NULL, license_category VARCHAR(255) NOT NULL,
 company_name VARCHAR(300) NOT NULL, postal_address TEXT, region VARCHAR(120), email_address VARCHAR(255),
 tin_no VARCHAR(80), tel_no VARCHAR(80), license_no VARCHAR(120), issued_date DATE, expire_date DATE,
 created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP)");
 $cols=['license_sale_season'=>'VARCHAR(20)','license_category'=>'VARCHAR(255)','company_name'=>'VARCHAR(300)','postal_address'=>'TEXT','region'=>'VARCHAR(120)','email_address'=>'VARCHAR(255)','tin_no'=>'VARCHAR(80)','tel_no'=>'VARCHAR(80)','license_no'=>'VARCHAR(120)','issued_date'=>'DATE','expire_date'=>'DATE','created_at'=>'TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP','updated_at'=>'TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP'];
 $q=$db->prepare("SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='coffee_licenses' AND column_name=:c");
 foreach($cols as $c=>$t){$q->execute(['c'=>$c]);if(!$q->fetchColumn())$db->exec('ALTER TABLE public.coffee_licenses ADD COLUMN "'.$c.'" '.$t);}
 $db->exec("CREATE INDEX IF NOT EXISTS idx_license_season ON public.coffee_licenses(license_sale_season)");
 $db->exec("CREATE INDEX IF NOT EXISTS idx_license_category ON public.coffee_licenses(license_category)");
 $db->exec("CREATE INDEX IF NOT EXISTS idx_license_region ON public.coffee_licenses(region)");
 $db->exec("CREATE INDEX IF NOT EXISTS idx_license_company ON public.coffee_licenses(company_name)");
}
function license_delete_all(): int {ensure_license_table();return license_db()->exec('DELETE FROM public.coffee_licenses');}
function lj(bool $ok,string $msg='',array $data=[],int $status=200):void{while(ob_get_level())ob_end_clean();http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode(['success'=>$ok,'message'=>$msg,'data'=>$data],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function lnrm($v):string{$s=strtolower(trim((string)$v));$s=preg_replace('/[^a-z0-9]+/','_',$s);return trim($s,'_');}
function ldate($v):?string{if($v===null)return null;$s=trim((string)$v);if($s===''||$s==='-')return null;if(is_numeric($s)&&((float)$s)>20000){$d=new DateTime('1899-12-30');$d->modify('+'.(int)floor((float)$s).' days');return $d->format('Y-m-d');}$ts=strtotime($s);return $ts===false?null:date('Y-m-d',$ts);}
function colidx(string $l):int{$n=0;foreach(str_split($l)as$c)$n=$n*26+(ord(strtoupper($c))-64);return$n-1;}
function parse_xlsx(string$f):array{if(!class_exists('ZipArchive'))throw new RuntimeException('ZipArchive is required to read Excel files.');$z=new ZipArchive();if($z->open($f)!==true)throw new RuntimeException('The Excel workbook could not be opened.');$ss=[];$x=$z->getFromName('xl/sharedStrings.xml');if($x!==false){$xml=simplexml_load_string($x);foreach($xml->si??[] as$si){$p=[];if(isset($si->t))$p[]=(string)$si->t;if(isset($si->r))foreach($si->r as$r)$p[]=(string)$r->t;$ss[]=implode('',$p);}}$sheet=$z->getFromName('xl/worksheets/sheet1.xml');if($sheet===false)throw new RuntimeException('Worksheet sheet1.xml was not found.');$xml=simplexml_load_string($sheet);$rows=[];foreach($xml->sheetData->row as$row){$o=[];foreach($row->c as$c){preg_match('/([A-Z]+)\d+/',(string)$c['r'],$m);$i=colidx($m[1]??'A');$t=(string)$c['t'];$v=$t==='s'?($ss[(int)$c->v]??''):($t==='inlineStr'?(string)$c->is->t:(string)$c->v);$o[$i]=$v;}if($o){ksort($o);$full=array_fill(0,max(array_keys($o))+1,'');foreach($o as$i=>$v)$full[$i]=$v;$rows[]=$full;}}$z->close();return$rows;}
function parse_file(string$f,string$ext):array{if(in_array($ext,['xlsx','xlsm','xltx'],true))return parse_xlsx($f);if($ext==='csv'){$a=[];$h=fopen($f,'rb');while(($r=fgetcsv($h))!==false)$a[]=$r;fclose($h);return$a;}throw new RuntimeException('Please upload .xlsx, .xlsm, .xltx or .csv.');}
function aliases():array{return['license_sale_season'=>['license_sale_season','sale_season','season'],'license_category'=>['license_category','category'],'company_name'=>['company_individual_name','company_name','company_individual'],'postal_address'=>['postal_address','address'],'region'=>['region'],'email_address'=>['email_address','email'],'tin_no'=>['tin_no','tin'],'tel_no'=>['tel_no','telephone_no','phone_no','telephone'],'license_no'=>['license_no','licence_no','license_number','licence_number'],'issued_date'=>['issued_date','issue_date'],'expire_date'=>['expire_date','expiry_date','expiration_date']];}
function maphead(array$h):array{$n=array_map('lnrm',$h);$m=[];foreach(aliases()as$f=>$aa){$m[$f]=null;foreach($aa as$a){$i=array_search($a,$n,true);if($i!==false){$m[$f]=$i;break;}}}return$m;}
function upload():void{if(!isset($_FILES['license_excel']))lj(false,'Please select the licence Excel file.',[],400);$f=$_FILES['license_excel'];if(($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)lj(false,'The selected file could not be uploaded.',[],400);try{$rows=parse_file($f['tmp_name'],strtolower(pathinfo($f['name'],PATHINFO_EXTENSION)));}catch(Throwable$e){lj(false,$e->getMessage(),[],400);}if(count($rows)<2)lj(false,'The workbook contains no licence data.',[],400);$hi=null;for($i=0;$i<min(15,count($rows));$i++){$m=maphead($rows[$i]);if($m['license_sale_season']!==null&&$m['license_category']!==null&&$m['company_name']!==null){$hi=$i;break;}}if($hi===null)lj(false,'Could not identify the licence header row. Expected the 11-column licence template.',[],400);$m=maphead($rows[$hi]);$missing=[];foreach($m as$k=>$v)if($v===null)$missing[]=$k;if($missing)lj(false,'Upload stopped. Missing column(s): '.implode(', ',$missing).'.',[],400);
 $records=[];$errors=[];for($ri=$hi+1;$ri<count($rows);$ri++){$r=$rows[$ri];$g=fn($k)=>trim((string)($r[$m[$k]]??''));$season=$g('license_sale_season');$cat=$g('license_category');$company=$g('company_name');if($season===''&&$cat===''&&$company==='')continue;if($season===''||$cat===''||$company===''){$errors[]=$ri+1;continue;}$records[]=['license_sale_season'=>$season,'license_category'=>$cat,'company_name'=>$company,'postal_address'=>$g('postal_address'),'region'=>$g('region'),'email_address'=>$g('email_address'),'tin_no'=>$g('tin_no'),'tel_no'=>$g('tel_no'),'license_no'=>($g('license_no')==='-'?'':$g('license_no')),'issued_date'=>ldate($g('issued_date')),'expire_date'=>ldate($g('expire_date'))];}
 if($errors)lj(false,'Some rows are missing mandatory Season, Category or Company/Individual Name. Nothing was uploaded.',['excel_rows'=>$errors],400);if(!$records)lj(false,'No valid licence records were found.',[],400);ensure_license_table();$db=license_db();$replace=($_POST['replace_seasons']??'')==='1';$seasons=array_values(array_unique(array_column($records,'license_sale_season')));if(!$replace){$ph=implode(',',array_fill(0,count($seasons),'?'));$q=$db->prepare("SELECT license_sale_season,COUNT(*) n FROM public.coffee_licenses WHERE license_sale_season IN ($ph) GROUP BY license_sale_season");$q->execute($seasons);$existing=$q->fetchAll();if($existing)lj(true,'Existing records were found for one or more uploaded seasons. Confirm replacement to avoid duplicates.',['requires_confirmation'=>true,'existing'=>$existing,'incoming'=>count($records)]);}
 $db->beginTransaction();try{if($replace){$ph=implode(',',array_fill(0,count($seasons),'?'));$d=$db->prepare("DELETE FROM public.coffee_licenses WHERE license_sale_season IN ($ph)");$d->execute($seasons);}$ins=$db->prepare("INSERT INTO public.coffee_licenses(license_sale_season,license_category,company_name,postal_address,region,email_address,tin_no,tel_no,license_no,issued_date,expire_date) VALUES(:license_sale_season,:license_category,:company_name,:postal_address,:region,:email_address,:tin_no,:tel_no,:license_no,:issued_date,:expire_date)");foreach($records as$r)$ins->execute($r);$db->commit();}catch(Throwable$e){if($db->inTransaction())$db->rollBack();error_log('Licence upload: '.$e->getMessage());lj(false,'Licence records could not be saved.',[],500);}lj(true,'Licence data uploaded successfully.',['processed'=>count($records),'seasons'=>$seasons]);}
function filters():void{ensure_license_table();$db=license_db();lj(true,'',['seasons'=>$db->query("SELECT DISTINCT license_sale_season FROM public.coffee_licenses WHERE BTRIM(COALESCE(license_sale_season,''))<>'' ORDER BY license_sale_season DESC")->fetchAll(PDO::FETCH_COLUMN),'categories'=>$db->query("SELECT DISTINCT license_category FROM public.coffee_licenses WHERE BTRIM(COALESCE(license_category,''))<>'' ORDER BY license_category")->fetchAll(PDO::FETCH_COLUMN),'regions'=>$db->query("SELECT DISTINCT region FROM public.coffee_licenses WHERE BTRIM(COALESCE(region,''))<>'' ORDER BY region")->fetchAll(PDO::FETCH_COLUMN)]);}
function fetchrows():void{ensure_license_table();$db=license_db();$w=[];$p=[];foreach(['season'=>'license_sale_season','category'=>'license_category','region'=>'region']as$q=>$c){$v=trim($_GET[$q]??'');if($v!==''){$w[]="$c=:$q";$p[$q]=$v;}}$search=trim($_GET['search']??'');if($search!==''){$w[]="(company_name ILIKE :s OR COALESCE(license_no,'') ILIKE :s OR COALESCE(tin_no,'') ILIKE :s OR COALESCE(tel_no,'') ILIKE :s OR COALESCE(email_address,'') ILIKE :s)";$p['s']='%'.$search.'%';}$sql="SELECT id,license_sale_season,license_category,company_name,postal_address,region,email_address,tin_no,tel_no,license_no,TO_CHAR(issued_date,'DD/MM/YYYY') issued_date,TO_CHAR(expire_date,'DD/MM/YYYY') expire_date FROM public.coffee_licenses".($w?' WHERE '.implode(' AND ',$w):'')." ORDER BY license_sale_season DESC,license_category,company_name";$q=$db->prepare($sql);$q->execute($p);$rows=$q->fetchAll();lj(true,'',['rows'=>$rows,'count'=>count($rows)]);}
function stats():void{ensure_license_table();$db=license_db();$season=trim($_GET['season']??'');$w=$season!==''?' WHERE license_sale_season=:s':'';$p=$season!==''?['s'=>$season]:[];$q=$db->prepare("SELECT COUNT(*) total,COUNT(DISTINCT company_name) entities,COUNT(DISTINCT license_category) categories,COUNT(DISTINCT NULLIF(BTRIM(region),'')) regions FROM public.coffee_licenses$w");$q->execute($p);$summary=$q->fetch();$q=$db->prepare("SELECT license_category label,COUNT(*) value FROM public.coffee_licenses$w GROUP BY license_category ORDER BY value DESC,label");$q->execute($p);$cats=$q->fetchAll();$q=$db->prepare("SELECT COALESCE(NULLIF(BTRIM(region),''),'Unspecified') label,COUNT(*) value FROM public.coffee_licenses$w GROUP BY 1 ORDER BY value DESC,label");$q->execute($p);lj(true,'',['summary'=>$summary,'categories'=>$cats,'regions'=>$q->fetchAll()]);}
function update():void{ensure_license_table();$db=license_db();$in=json_decode(file_get_contents('php://input'),true)?:[];$id=(int)($in['id']??0);if($id<=0)lj(false,'Invalid licence row.',[],400);$fields=['license_sale_season','license_category','company_name','postal_address','region','email_address','tin_no','tel_no','license_no','issued_date','expire_date'];$set=[];$p=['id'=>$id];foreach($fields as$f)if(array_key_exists($f,$in)){$v=$in[$f];if(in_array($f,['issued_date','expire_date'],true))$v=ldate($v);$set[]="$f=:$f";$p[$f]=$v;}if(!$set)lj(false,'No changes supplied.',[],400);$q=$db->prepare('UPDATE public.coffee_licenses SET '.implode(',',$set).',updated_at=CURRENT_TIMESTAMP WHERE id=:id');$q->execute($p);lj(true,'Licence record updated successfully.');}
function del():void{ensure_license_table();$in=json_decode(file_get_contents('php://input'),true)?:[];$id=(int)($in['id']??0);if($id<=0)lj(false,'Invalid licence row.',[],400);$q=license_db()->prepare('DELETE FROM public.coffee_licenses WHERE id=:id');$q->execute(['id'=>$id]);lj(true,'Licence record deleted successfully.');}
try{if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'&&isset($_FILES['license_excel']))upload();$a=$_GET['action']??'';if($a==='filters')filters();if($a==='fetch')fetchrows();if($a==='stats')stats();if($a==='update'&&($_SERVER['REQUEST_METHOD']??'')==='POST')update();if($a==='delete'&&($_SERVER['REQUEST_METHOD']??'')==='POST')del();if($a==='delete_all'&&($_SERVER['REQUEST_METHOD']??'')==='POST')lj(true,'All licence data deleted.',['deleted'=>license_delete_all()]);ensure_license_table();}catch(Throwable $e){
    error_log('Licences: '.$e->getMessage());
    if(isset($_GET['action'])||($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
        lj(false,'Licence operation failed. '.$e->getMessage(),[],500);
    }
    /* Never leave the normal module page blank if PostgreSQL initialization fails. */
    $license_page_error=$e->getMessage();
}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Coffee Licences</title><style>
*{box-sizing:border-box}html,body{margin:0;height:100%;font-family:Arial,sans-serif;background:#f7f4f2;color:#382b26}body{overflow:hidden}.app{height:100vh;padding:8px;display:grid;grid-template-rows:auto auto auto minmax(0,1fr);gap:6px}.toolbar,.filters{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.toolbar{justify-content:space-between}.title{font-size:15px;font-weight:800;color:#4b342c}.muted{font-size:9px;color:#8b7d77}.controls{display:flex;gap:5px;align-items:center;flex-wrap:wrap}select,button,input{height:30px;border:1px solid #d9cfca;border-radius:6px;background:#fff;padding:0 9px;font-size:11px;color:#4b342c}button{cursor:pointer;font-weight:700}.primary{background:#5d4037;color:#fff;border-color:#5d4037}.danger{color:#9a2f28}.settings{position:relative}.menu{display:none;position:absolute;right:0;top:34px;background:#fff;border:1px solid #ddd2cd;border-radius:7px;padding:6px;min-width:180px;z-index:30;box-shadow:0 8px 22px #0002}.menu.open{display:block}.menu button{width:100%;text-align:left;border:0}.uploadbox{display:none;gap:5px;align-items:center}.uploadbox.open{display:flex}.msg{font-size:10px;padding:5px 8px;border-radius:5px;display:none}.msg.ok{display:block;background:#eaf5ec;color:#276536}.msg.err{display:block;background:#faecea;color:#8a3029}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.kpi{background:#fff;border:1px solid #e6ddd9;border-radius:7px;padding:7px 9px}.kpi span{font-size:8px;color:#8b7d77;text-transform:uppercase}.kpi strong{display:block;font-size:16px;color:#4b342c;margin-top:2px}.card{min-height:0;background:#fff;border:1px solid #e6ddd9;border-radius:8px;overflow:hidden;display:flex;flex-direction:column}.tablewrap{min-height:0;overflow:auto;flex:1}table{border-collapse:collapse;width:100%;min-width:1500px;font-size:9px}th,td{padding:5px 6px;border-bottom:1px solid #eee7e4;white-space:nowrap;text-align:left}thead th{position:sticky;top:0;background:#4b342c;color:#fff;z-index:3;font-size:8px}.actions{display:none}.editmode .actions{display:table-cell}.rowbtn{height:23px;padding:0 5px;font-size:9px}.count{font-size:9px;color:#776861;margin-left:auto}.search{min-width:180px}.export{background:#fff}@media(max-width:900px){body{overflow:auto}.app{height:auto;min-height:100vh}.kpis{grid-template-columns:repeat(2,1fr)}.card{min-height:70vh}.filters>*{flex:1 1 150px}}@media(max-width:600px){.app{padding:5px}.kpis{grid-template-columns:1fr 1fr}.uploadbox.open{width:100%;flex-wrap:wrap}.title{font-size:13px}}
</style></head><body><div class="app"><?php if(!empty($license_page_error)): ?><div class="msg err" style="display:block"><strong>Licence module database error:</strong> <?= htmlspecialchars($license_page_error, ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?><div class="toolbar"><div><span class="title">Coffee Licences</span> <span class="muted">Licence register stored in PostgreSQL</span></div><div class="controls"><button class="export" onclick="exportCsv()">⇩ Export CSV</button><div class="settings"><button onclick="toggleSettings(event)">⚙ Settings</button><div class="menu" id="settings"><button onclick="showUpload()">↑ Upload Licence Excel</button><button onclick="toggleEdit()">✎ Edit records</button><button class="danger" onclick="deleteAll()">⌫ Delete all data</button></div></div></div></div>
<div><div class="filters"><select id="season"><option value="">All Sale Seasons</option></select><select id="category"><option value="">All Licence Categories</option></select><select id="region"><option value="">All Regions</option></select><input id="search" class="search" placeholder="Search company, licence, TIN, tel..."><button onclick="refresh()">↻ Refresh</button><div class="uploadbox" id="uploadbox"><input type="file" id="file" accept=".xlsx,.xlsm,.xltx,.csv"><button class="primary" onclick="upload(false)">Upload Licences</button></div><span class="count" id="count"></span></div><div class="msg" id="msg"></div></div>
<div class="kpis"><div class="kpi"><span>Licence Records</span><strong id="kTotal">0</strong></div><div class="kpi"><span>Companies / Individuals</span><strong id="kEntities">0</strong></div><div class="kpi"><span>Licence Categories</span><strong id="kCategories">0</strong></div><div class="kpi"><span>Regions</span><strong id="kRegions">0</strong></div></div>
<div class="card" id="card"><div class="tablewrap"><table id="table"></table></div></div></div><script>
const $=id=>document.getElementById(id);const cols=[['license_sale_season','Sale Season'],['license_category','Licence Category'],['company_name','Company / Individual Name'],['postal_address','Postal Address'],['region','Region'],['email_address','Email Address'],['tin_no','TIN No.'],['tel_no','Tel. No.'],['license_no','Licence No.'],['issued_date','Issued Date'],['expire_date','Expire Date']];let rows=[],edit=false;
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function msg(t,ok=true){let m=$('msg');m.className='msg '+(ok?'ok':'err');m.textContent=t;setTimeout(()=>m.className='msg',6500)}async function api(u,o){let r=await fetch(u,o),j=await r.json();if(!r.ok||j.success===false)throw new Error(j.message||'Request failed');return j.data}
function toggleSettings(e){e?.stopPropagation();$('settings').classList.toggle('open')}document.addEventListener('click',e=>{if(!e.target.closest('.settings'))$('settings').classList.remove('open')});function showUpload(){$('settings').classList.remove('open');$('uploadbox').classList.toggle('open')}function toggleEdit(){edit=!edit;$('card').classList.toggle('editmode',edit);$('settings').classList.remove('open');render()}
async function loadFilters(){let d=await api('licenses.php?action=filters');const fill=(id,a,label)=>{$(id).innerHTML=`<option value="">${label}</option>`+a.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')};fill('season',d.seasons,'All Sale Seasons');fill('category',d.categories,'All Licence Categories');fill('region',d.regions,'All Regions')}
function qs(){let p=new URLSearchParams();['season','category','region','search'].forEach(k=>{let v=$(k).value.trim();if(v)p.set(k,v)});return p.toString()}
async function loadRows(){let d=await api('licenses.php?action=fetch&'+qs());rows=d.rows;$('count').textContent=d.count.toLocaleString()+' record(s)';render()}async function loadStats(){let p=new URLSearchParams();if($('season').value)p.set('season',$('season').value);let d=await api('licenses.php?action=stats&'+p);$('kTotal').textContent=Number(d.summary.total||0).toLocaleString();$('kEntities').textContent=Number(d.summary.entities||0).toLocaleString();$('kCategories').textContent=Number(d.summary.categories||0).toLocaleString();$('kRegions').textContent=Number(d.summary.regions||0).toLocaleString()}
function render(){let h='<thead><tr>'+cols.map(c=>`<th>${c[1]}</th>`).join('')+'<th class="actions">Actions</th></tr></thead><tbody>';for(const r of rows){h+='<tr>'+cols.map(c=>`<td>${esc(r[c[0]]||'')}</td>`).join('')+`<td class="actions"><button class="rowbtn" onclick="editRow(${r.id})">Edit</button> <button class="rowbtn danger" onclick="deleteRow(${r.id})">Delete</button></td></tr>`}h+='</tbody>';$('table').innerHTML=h}
async function refresh(){try{await Promise.all([loadRows(),loadStats()])}catch(e){msg(e.message,false)}}['season','category','region'].forEach(id=>$(id).addEventListener('change',refresh));let st;$('search').addEventListener('input',()=>{clearTimeout(st);st=setTimeout(loadRows,300)})
async function upload(confirmReplace){let f=$('file').files[0];if(!f){msg('Select the licence Excel file first.',false);return}let fd=new FormData();fd.append('license_excel',f);if(confirmReplace)fd.append('replace_seasons','1');try{let r=await fetch('licenses.php',{method:'POST',body:fd}),j=await r.json();if(!r.ok||j.success===false)throw new Error(j.message||'Upload failed');if(j.data?.requires_confirmation){let detail=(j.data.existing||[]).map(x=>`${x.license_sale_season}: ${x.n} existing`).join('\n');if(confirm('Existing licence data was found:\n'+detail+'\n\nReplace the existing data for these season(s) with this workbook?'))return upload(true);return}msg(j.message);await loadFilters();await refresh()}catch(e){msg(e.message,false)}}
async function editRow(id){let r=rows.find(x=>Number(x.id)===Number(id));if(!r)return;let out={id};for(const [k,label] of cols){let v=prompt(label,r[k]??'');if(v===null)return;out[k]=v}try{await api('licenses.php?action=update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(out)});msg('Licence record updated.');await loadFilters();await refresh()}catch(e){msg(e.message,false)}}async function deleteRow(id){if(!confirm('Delete this licence record?'))return;try{await api('licenses.php?action=delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});msg('Licence record deleted.');await refresh()}catch(e){msg(e.message,false)}}async function deleteAll(){if(!confirm('Delete ALL licence records from the database? This cannot be undone.'))return;try{await api('licenses.php?action=delete_all',{method:'POST'});msg('All licence records deleted.');await loadFilters();await refresh()}catch(e){msg(e.message,false)}}
function exportCsv(){if(!rows.length){msg('There is no displayed licence data to export.',false);return}let q=s=>`"${String(s??'').replace(/"/g,'""')}"`;let csv=[cols.map(c=>q(c[1])).join(',')].concat(rows.map(r=>cols.map(c=>q(r[c[0]])).join(','))).join('\r\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff',csv],{type:'text/csv;charset=utf-8'}));a.download='Coffee_Licences_'+($('season').value||'All_Seasons').replace('/','-')+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
(async()=>{try{await loadFilters();await refresh()}catch(e){msg(e.message,false)}})();</script></body></html>
